### ISSUE TITLE
Create default indexes

### ISSUE THREAD

**Issue by carlosms** [src-d/metadata-retrieval#2] opened 2019-09-24 16:59 UTC
This issue is to discuss if we want to create default indexes for the current DB schema, and which ones.

**Comment by se7entyse7en** [comment] 2019-09-27 09:32
I'm wondering whether this issue fits more in sourced-ui given that it's the actual consumer of the data and so it's the only one aware of which indexes are useful or not. I mean if we want this to be a standalone library, I don't think it makes much sense to add any specific index. On the other hand in `sourced-ui` we could also include some regression tests that track the average time for the queries available in the default dashboards everytime an index or a dashboard is changed.

**Comment by se7entyse7en** [comment] 2019-10-17 09:20
Moving this back to the backlog as lacking specific definition. This needs to be discussed also wrt to the underlying the db engine we're going to use if we replace gitbase. It doesn't make sense to think about this now.

**Comment by smacker** [comment] 2019-10-17 10:13
we should at least add constraints

**Comment by se7entyse7en** [comment] 2019-10-18 15:12
> we should at least add constraints

right, I'd discuss this once we have at least the unified schema, wdyt?

And regarding this:

> On the other hand in sourced-ui we could also include some regression tests that track the average time for the queries available in the default dashboards every time an index or a dashboard is changed.

I'd like to hear also opinion from @src-d/qa. BTW this is just an idea so far, but I think it would be interesting.

**Comment by kyrcha** [comment] 2019-10-22 08:11
As a @src-d/qa team we have in plan to create also:

- a regression testing suite: (like https://github.com/src-d/regression-gitbase)
- a performance testing suite (like https://github.com/bblfsh/performance)

for metadata-retrieval. 

I agree with the premise that indices should be driven by the use case.

**Comment by se7entyse7en** [comment] 2019-10-22 08:46
Maybe it's too early now for this, but I'd still keep in mind the idea of possibly having a performance testing suite for sourced-ui as well in the future.

Since I created a separate issue for constraints in db schema, I'm closing this.

**Closed by se7entyse7en** 2019-10-22 08:46 UTC
Labels: enhancement, needs discussion/agreement
